sonar.projectKey=portus84_smartorder-ms
sonar.organization=portus84
sonar.projectName=smartorder-ms

sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/generated/**,**/config/**,**/tmp/**,**/openapi/**

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml,target/site/jacoco/jacoco.xml
