package rules.order

import it.portus.smartorder.ms.orderservice.business.domain.model.Order
import it.portus.smartorder.ms.orderservice.business.rules.order.strategy.impl.StatusTransitionStrategy.OrderTransition
import it.portus.smartorder.ms.orderservice.business.rules.order.strategy.impl.StatusTransitionStrategy.ValidTransition

rule "Invalid transition"
ruleflow-group "validation"
when
    $order : Order( $id : id, $current : status )
    $trans : OrderTransition( orderId == $id, $target : targetStatus )
    not ValidTransition( current == $current, next == $target )
then
    throw new RuntimeException(
        "Invalid transition from " + $current + " to " + $target
    );
end
