sourceFolder: src/gen/java

#ignoreFileOverride: ../.openapi-generator-ignore

apiPackage: it.portus.smartorder.ms.orderservice.api.v1.openapi
modelPackage: it.portus.smartorder.ms.orderservice.api.v1.openapi.model
invokerPackage: it.portus.smartorder.ms.orderservice.api.v1.openapi.invoker
configPackage: it.portus.smartorder.ms.orderservice.api.v1.openapi.configuration

openapiNormalizer:
  REF_AS_PARENT_IN_ALLOF: true
  SIMPLIFY_ONEOF_ANYOF: true
  SIMPLIFY_BOOLEAN_ENUM: true

useSpringBoot3: true
useTags: true
useJakartaEe: true
#hateoas: true
delegatePattern: true
openApiNullable: false
performBeanValidation: true
useBeanValidation: true
dateLibrary: java8-localdatetime
skipDefaultContentType: true

hideGenerationTimestamp: true

generateApiTests: false
generateModelTests: false

additionalModelTypeAnnotations: |
  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL);
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
#  @lombok.NoArgsConstructor
#  @lombok.AllArgsConstructor

importMappings:
  ErrorResponse: it.portus.ms.commons.dto.ErrorResponse

typeMappings:
  ErrorResponse: it.portus.ms.commons.dto.ErrorResponse

inlineSchemaNameMappings:
  #Pageable_sort: Sort
  #Pageable_sort_orders_inner: SortOrder
  PageOrder_allOf__embedded: PageOrderEmbedded

schemaMappings:
  ErrorResponse: it.portus.ms.commons.dto.ErrorResponse
  PageMetadata: it.portus.ms.commons.dto.PageMetadata
  #Sort: org.springframework.data.domain.Sort
  #SortOrder: org.springframework.data.domain.Sort.Order
  RepresentationModel: org.springframework.hateoas.RepresentationModel
  PagedModel: org.springframework.hateoas.PagedModel
  Links: org.springframework.hateoas.Links
  Link: org.springframework.hateoas.Link
